#!/bin/bash

# Get stalkerware-urls and put into rpz format

RPZFileTMP='/tmp/db.rpz.local'
RPZFile='/etc/bind/db.rpz.local'
on_err() {

	echo "$1"
	exit 1

}
# Get the URLs from https://github.com/astryzia/stalkerware-urls/blob/main/stalkerware_urls.txt
curl https://raw.githubusercontent.com/astryzia/stalkerware-urls/main/stalkerware_urls.txt -o stalkerware_urls.txt

RPZContents='; BIND reverse data file for empty rfc1918 zone
;
; DO NOT EDIT THIS FILE - it is used for multiple zones.
; Instead, copy it, edit named.conf, and use that copy.
;
$TTL	86400
@	IN	SOA	localhost. root.localhost. (
			      1		; Serial
			 604800		; Refresh
			  86400		; Retry
			2419200		; Expire
			  86400 )	; Negative Cache TTL
;
@	IN	NS	localhost.'


# Write RPZContents to RPZFileTMP first and check for errors.
echo "${RPZContents}" > ${RPZFileTMP}

# Loop through the results and put into RPZ block format
for each_url in $(cat stalkerware_urls.txt); do

	echo "${each_url}	CNAME	." >> ${RPZFileTMP}

done

# Check there are no errors with new rules
sudo named-checkzone rpz ${RPZFileTMP}

if [[ $? -ne 0 ]]; then

	on_err "Error found in the RPZ file format."

else

	echo "Moving TMP file to ${RPZFile}"
	mv ${RPZFileTMP} ${RPZFile}
	echo "Restarting bind 9"
	sudo systemctl restart bind9

fi
